// Mocks generated by Mockito 5.4.4 from annotations
// in prioris/test/presentation/controllers/lists_controller_adaptive_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prioris/data/repositories/custom_list_repository.dart' as _i2;
import 'package:prioris/data/repositories/list_item_repository.dart' as _i3;
import 'package:prioris/domain/models/core/entities/custom_list.dart' as _i6;
import 'package:prioris/domain/models/core/entities/list_item.dart' as _i7;
import 'package:prioris/domain/models/core/enums/list_enums.dart' as _i9;
import 'package:prioris/domain/services/core/lists_filter_service.dart' as _i8;
import 'package:prioris/domain/services/persistence/adaptive_persistence_service.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCustomListRepository_0 extends _i1.SmartFake
    implements _i2.CustomListRepository {
  _FakeCustomListRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListItemRepository_1 extends _i1.SmartFake
    implements _i3.ListItemRepository {
  _FakeListItemRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdaptivePersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdaptivePersistenceService extends _i1.Mock
    implements _i4.AdaptivePersistenceService {
  MockAdaptivePersistenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CustomListRepository get localRepository => (super.noSuchMethod(
        Invocation.getter(#localRepository),
        returnValue: _FakeCustomListRepository_0(
          this,
          Invocation.getter(#localRepository),
        ),
      ) as _i2.CustomListRepository);

  @override
  _i2.CustomListRepository get cloudRepository => (super.noSuchMethod(
        Invocation.getter(#cloudRepository),
        returnValue: _FakeCustomListRepository_0(
          this,
          Invocation.getter(#cloudRepository),
        ),
      ) as _i2.CustomListRepository);

  @override
  _i3.ListItemRepository get localItemRepository => (super.noSuchMethod(
        Invocation.getter(#localItemRepository),
        returnValue: _FakeListItemRepository_1(
          this,
          Invocation.getter(#localItemRepository),
        ),
      ) as _i3.ListItemRepository);

  @override
  _i3.ListItemRepository get cloudItemRepository => (super.noSuchMethod(
        Invocation.getter(#cloudItemRepository),
        returnValue: _FakeListItemRepository_1(
          this,
          Invocation.getter(#cloudItemRepository),
        ),
      ) as _i3.ListItemRepository);

  @override
  _i4.PersistenceMode get currentMode => (super.noSuchMethod(
        Invocation.getter(#currentMode),
        returnValue: _i4.PersistenceMode.localFirst,
      ) as _i4.PersistenceMode);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize({bool? isAuthenticated}) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {#isAuthenticated: isAuthenticated},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateAuthenticationState(
          {required bool? isAuthenticated}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAuthenticationState,
          [],
          {#isAuthenticated: isAuthenticated},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.CustomList>> getAllLists() => (super.noSuchMethod(
        Invocation.method(
          #getAllLists,
          [],
        ),
        returnValue: _i5.Future<List<_i6.CustomList>>.value(<_i6.CustomList>[]),
      ) as _i5.Future<List<_i6.CustomList>>);

  @override
  _i5.Future<List<_i6.CustomList>> getLists() => (super.noSuchMethod(
        Invocation.method(
          #getLists,
          [],
        ),
        returnValue: _i5.Future<List<_i6.CustomList>>.value(<_i6.CustomList>[]),
      ) as _i5.Future<List<_i6.CustomList>>);

  @override
  _i5.Future<void> saveList(_i6.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #saveList,
          [list],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteList(String? listId) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [listId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.ListItem>> getItemsByListId(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByListId,
          [listId],
        ),
        returnValue: _i5.Future<List<_i7.ListItem>>.value(<_i7.ListItem>[]),
      ) as _i5.Future<List<_i7.ListItem>>);

  @override
  _i5.Future<List<_i7.ListItem>> getListItems(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListItems,
          [listId],
        ),
        returnValue: _i5.Future<List<_i7.ListItem>>.value(<_i7.ListItem>[]),
      ) as _i5.Future<List<_i7.ListItem>>);

  @override
  _i5.Future<void> saveItem(_i7.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #saveItem,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateItem(_i7.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteItem(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [itemId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ListsFilterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockListsFilterService extends _i1.Mock
    implements _i8.ListsFilterService {
  MockListsFilterService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.CustomList> applyFilters(
    List<_i6.CustomList>? lists, {
    String? searchQuery = r'',
    _i9.ListType? selectedType,
    bool? showCompleted = true,
    bool? showInProgress = true,
    String? selectedDateFilter,
    _i8.SortOption? sortOption = _i8.SortOption.NAME_ASC,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyFilters,
          [lists],
          {
            #searchQuery: searchQuery,
            #selectedType: selectedType,
            #showCompleted: showCompleted,
            #showInProgress: showInProgress,
            #selectedDateFilter: selectedDateFilter,
            #sortOption: sortOption,
          },
        ),
        returnValue: <_i6.CustomList>[],
      ) as List<_i6.CustomList>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
