// Mocks generated by Mockito 5.4.5 from annotations
// in prioris/test/performance/performance_optimization_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prioris/data/repositories/custom_list_repository.dart' as _i3;
import 'package:prioris/data/repositories/list_item_repository.dart' as _i7;
import 'package:prioris/domain/models/core/entities/custom_list.dart' as _i5;
import 'package:prioris/domain/models/core/entities/list_item.dart' as _i2;
import 'package:prioris/domain/models/core/enums/list_enums.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeListItem_0 extends _i1.SmartFake implements _i2.ListItem {
  _FakeListItem_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CustomListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomListRepository extends _i1.Mock
    implements _i3.CustomListRepository {
  MockCustomListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.CustomList>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<List<_i5.CustomList>>.value(<_i5.CustomList>[]),
      ) as _i4.Future<List<_i5.CustomList>>);

  @override
  _i4.Future<_i5.CustomList?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i4.Future<_i5.CustomList?>.value(),
      ) as _i4.Future<_i5.CustomList?>);

  @override
  _i4.Future<void> save(_i5.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [list],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> update(_i5.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [list],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.CustomList>> getAllLists() => (super.noSuchMethod(
        Invocation.method(
          #getAllLists,
          [],
        ),
        returnValue: _i4.Future<List<_i5.CustomList>>.value(<_i5.CustomList>[]),
      ) as _i4.Future<List<_i5.CustomList>>);

  @override
  _i4.Future<_i5.CustomList?> getListById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getListById,
          [id],
        ),
        returnValue: _i4.Future<_i5.CustomList?>.value(),
      ) as _i4.Future<_i5.CustomList?>);

  @override
  _i4.Future<void> saveList(_i5.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #saveList,
          [list],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateList(_i5.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #updateList,
          [list],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteList(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.CustomList>> searchByName(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByName,
          [query],
        ),
        returnValue: _i4.Future<List<_i5.CustomList>>.value(<_i5.CustomList>[]),
      ) as _i4.Future<List<_i5.CustomList>>);

  @override
  _i4.Future<List<_i5.CustomList>> searchByDescription(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByDescription,
          [query],
        ),
        returnValue: _i4.Future<List<_i5.CustomList>>.value(<_i5.CustomList>[]),
      ) as _i4.Future<List<_i5.CustomList>>);

  @override
  _i4.Future<List<_i5.CustomList>> searchListsByName(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchListsByName,
          [query],
        ),
        returnValue: _i4.Future<List<_i5.CustomList>>.value(<_i5.CustomList>[]),
      ) as _i4.Future<List<_i5.CustomList>>);

  @override
  _i4.Future<List<_i5.CustomList>> searchListsByDescription(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchListsByDescription,
          [query],
        ),
        returnValue: _i4.Future<List<_i5.CustomList>>.value(<_i5.CustomList>[]),
      ) as _i4.Future<List<_i5.CustomList>>);

  @override
  _i4.Future<List<_i5.CustomList>> getByType(_i6.ListType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByType,
          [type],
        ),
        returnValue: _i4.Future<List<_i5.CustomList>>.value(<_i5.CustomList>[]),
      ) as _i4.Future<List<_i5.CustomList>>);

  @override
  _i4.Future<List<_i5.CustomList>> getListsByType(_i6.ListType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListsByType,
          [type],
        ),
        returnValue: _i4.Future<List<_i5.CustomList>>.value(<_i5.CustomList>[]),
      ) as _i4.Future<List<_i5.CustomList>>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllLists() => (super.noSuchMethod(
        Invocation.method(
          #clearAllLists,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ListItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockListItemRepository extends _i1.Mock
    implements _i7.ListItemRepository {
  MockListItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ListItem>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<List<_i2.ListItem>>.value(<_i2.ListItem>[]),
      ) as _i4.Future<List<_i2.ListItem>>);

  @override
  _i4.Future<_i2.ListItem?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i4.Future<_i2.ListItem?>.value(),
      ) as _i4.Future<_i2.ListItem?>);

  @override
  _i4.Future<_i2.ListItem> add(_i2.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [item],
        ),
        returnValue: _i4.Future<_i2.ListItem>.value(_FakeListItem_0(
          this,
          Invocation.method(
            #add,
            [item],
          ),
        )),
      ) as _i4.Future<_i2.ListItem>);

  @override
  _i4.Future<_i2.ListItem> update(_i2.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [item],
        ),
        returnValue: _i4.Future<_i2.ListItem>.value(_FakeListItem_0(
          this,
          Invocation.method(
            #update,
            [item],
          ),
        )),
      ) as _i4.Future<_i2.ListItem>);

  @override
  _i4.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.ListItem>> getByListId(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByListId,
          [listId],
        ),
        returnValue: _i4.Future<List<_i2.ListItem>>.value(<_i2.ListItem>[]),
      ) as _i4.Future<List<_i2.ListItem>>);
}
