// Mocks generated by Mockito 5.4.4 from annotations
// in prioris/test/fixes/persistence_verification_fix_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prioris/data/repositories/custom_list_repository.dart' as _i3;
import 'package:prioris/data/repositories/list_item_repository.dart' as _i4;
import 'package:prioris/domain/models/core/entities/custom_list.dart' as _i6;
import 'package:prioris/domain/models/core/entities/list_item.dart' as _i2;
import 'package:prioris/domain/models/core/enums/list_enums.dart' as _i7;
import 'package:prioris/domain/services/core/lists_filter_service.dart' as _i9;
import 'package:prioris/domain/services/persistence/adaptive_persistence_service.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeListItem_0 extends _i1.SmartFake implements _i2.ListItem {
  _FakeListItem_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCustomListRepository_1 extends _i1.SmartFake
    implements _i3.CustomListRepository {
  _FakeCustomListRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListItemRepository_2 extends _i1.SmartFake
    implements _i4.ListItemRepository {
  _FakeListItemRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CustomListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomListRepository extends _i1.Mock
    implements _i3.CustomListRepository {
  MockCustomListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Map<String, dynamic>> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<_i6.CustomList>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i5.Future<List<_i6.CustomList>>.value(<_i6.CustomList>[]),
      ) as _i5.Future<List<_i6.CustomList>>);

  @override
  _i5.Future<_i6.CustomList?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i5.Future<_i6.CustomList?>.value(),
      ) as _i5.Future<_i6.CustomList?>);

  @override
  _i5.Future<void> save(_i6.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [list],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> update(_i6.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [list],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.CustomList>> getAllLists() => (super.noSuchMethod(
        Invocation.method(
          #getAllLists,
          [],
        ),
        returnValue: _i5.Future<List<_i6.CustomList>>.value(<_i6.CustomList>[]),
      ) as _i5.Future<List<_i6.CustomList>>);

  @override
  _i5.Future<_i6.CustomList?> getListById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getListById,
          [id],
        ),
        returnValue: _i5.Future<_i6.CustomList?>.value(),
      ) as _i5.Future<_i6.CustomList?>);

  @override
  _i5.Future<void> saveList(_i6.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #saveList,
          [list],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateList(_i6.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #updateList,
          [list],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteList(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.CustomList>> searchByName(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByName,
          [query],
        ),
        returnValue: _i5.Future<List<_i6.CustomList>>.value(<_i6.CustomList>[]),
      ) as _i5.Future<List<_i6.CustomList>>);

  @override
  _i5.Future<List<_i6.CustomList>> searchByDescription(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByDescription,
          [query],
        ),
        returnValue: _i5.Future<List<_i6.CustomList>>.value(<_i6.CustomList>[]),
      ) as _i5.Future<List<_i6.CustomList>>);

  @override
  _i5.Future<List<_i6.CustomList>> searchListsByName(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchListsByName,
          [query],
        ),
        returnValue: _i5.Future<List<_i6.CustomList>>.value(<_i6.CustomList>[]),
      ) as _i5.Future<List<_i6.CustomList>>);

  @override
  _i5.Future<List<_i6.CustomList>> searchListsByDescription(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchListsByDescription,
          [query],
        ),
        returnValue: _i5.Future<List<_i6.CustomList>>.value(<_i6.CustomList>[]),
      ) as _i5.Future<List<_i6.CustomList>>);

  @override
  _i5.Future<List<_i6.CustomList>> getByType(_i7.ListType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByType,
          [type],
        ),
        returnValue: _i5.Future<List<_i6.CustomList>>.value(<_i6.CustomList>[]),
      ) as _i5.Future<List<_i6.CustomList>>);

  @override
  _i5.Future<List<_i6.CustomList>> getListsByType(_i7.ListType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListsByType,
          [type],
        ),
        returnValue: _i5.Future<List<_i6.CustomList>>.value(<_i6.CustomList>[]),
      ) as _i5.Future<List<_i6.CustomList>>);

  @override
  _i5.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllLists() => (super.noSuchMethod(
        Invocation.method(
          #clearAllLists,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ListItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockListItemRepository extends _i1.Mock
    implements _i4.ListItemRepository {
  MockListItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.ListItem>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i5.Future<List<_i2.ListItem>>.value(<_i2.ListItem>[]),
      ) as _i5.Future<List<_i2.ListItem>>);

  @override
  _i5.Future<_i2.ListItem?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i5.Future<_i2.ListItem?>.value(),
      ) as _i5.Future<_i2.ListItem?>);

  @override
  _i5.Future<_i2.ListItem> add(_i2.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [item],
        ),
        returnValue: _i5.Future<_i2.ListItem>.value(_FakeListItem_0(
          this,
          Invocation.method(
            #add,
            [item],
          ),
        )),
      ) as _i5.Future<_i2.ListItem>);

  @override
  _i5.Future<_i2.ListItem> update(_i2.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [item],
        ),
        returnValue: _i5.Future<_i2.ListItem>.value(_FakeListItem_0(
          this,
          Invocation.method(
            #update,
            [item],
          ),
        )),
      ) as _i5.Future<_i2.ListItem>);

  @override
  _i5.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.ListItem>> getByListId(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByListId,
          [listId],
        ),
        returnValue: _i5.Future<List<_i2.ListItem>>.value(<_i2.ListItem>[]),
      ) as _i5.Future<List<_i2.ListItem>>);
}

/// A class which mocks [AdaptivePersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdaptivePersistenceService extends _i1.Mock
    implements _i8.AdaptivePersistenceService {
  MockAdaptivePersistenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CustomListRepository get localRepository => (super.noSuchMethod(
        Invocation.getter(#localRepository),
        returnValue: _FakeCustomListRepository_1(
          this,
          Invocation.getter(#localRepository),
        ),
      ) as _i3.CustomListRepository);

  @override
  _i3.CustomListRepository get cloudRepository => (super.noSuchMethod(
        Invocation.getter(#cloudRepository),
        returnValue: _FakeCustomListRepository_1(
          this,
          Invocation.getter(#cloudRepository),
        ),
      ) as _i3.CustomListRepository);

  @override
  _i4.ListItemRepository get localItemRepository => (super.noSuchMethod(
        Invocation.getter(#localItemRepository),
        returnValue: _FakeListItemRepository_2(
          this,
          Invocation.getter(#localItemRepository),
        ),
      ) as _i4.ListItemRepository);

  @override
  _i4.ListItemRepository get cloudItemRepository => (super.noSuchMethod(
        Invocation.getter(#cloudItemRepository),
        returnValue: _FakeListItemRepository_2(
          this,
          Invocation.getter(#cloudItemRepository),
        ),
      ) as _i4.ListItemRepository);

  @override
  _i8.PersistenceMode get currentMode => (super.noSuchMethod(
        Invocation.getter(#currentMode),
        returnValue: _i8.PersistenceMode.localFirst,
      ) as _i8.PersistenceMode);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize({bool? isAuthenticated}) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {#isAuthenticated: isAuthenticated},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateAuthenticationState(
          {required bool? isAuthenticated}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAuthenticationState,
          [],
          {#isAuthenticated: isAuthenticated},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.CustomList>> getAllLists() => (super.noSuchMethod(
        Invocation.method(
          #getAllLists,
          [],
        ),
        returnValue: _i5.Future<List<_i6.CustomList>>.value(<_i6.CustomList>[]),
      ) as _i5.Future<List<_i6.CustomList>>);

  @override
  _i5.Future<List<_i6.CustomList>> getLists() => (super.noSuchMethod(
        Invocation.method(
          #getLists,
          [],
        ),
        returnValue: _i5.Future<List<_i6.CustomList>>.value(<_i6.CustomList>[]),
      ) as _i5.Future<List<_i6.CustomList>>);

  @override
  _i5.Future<void> saveList(_i6.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #saveList,
          [list],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteList(String? listId) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [listId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.ListItem>> getItemsByListId(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByListId,
          [listId],
        ),
        returnValue: _i5.Future<List<_i2.ListItem>>.value(<_i2.ListItem>[]),
      ) as _i5.Future<List<_i2.ListItem>>);

  @override
  _i5.Future<List<_i2.ListItem>> getListItems(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListItems,
          [listId],
        ),
        returnValue: _i5.Future<List<_i2.ListItem>>.value(<_i2.ListItem>[]),
      ) as _i5.Future<List<_i2.ListItem>>);

  @override
  _i5.Future<void> saveItem(_i2.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #saveItem,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateItem(_i2.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteItem(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [itemId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ListsFilterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockListsFilterService extends _i1.Mock
    implements _i9.ListsFilterService {
  MockListsFilterService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.CustomList> applyFilters(
    List<_i6.CustomList>? lists, {
    String? searchQuery = r'',
    _i7.ListType? selectedType,
    bool? showCompleted = true,
    bool? showInProgress = true,
    String? selectedDateFilter,
    _i9.SortOption? sortOption = _i9.SortOption.NAME_ASC,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyFilters,
          [lists],
          {
            #searchQuery: searchQuery,
            #selectedType: selectedType,
            #showCompleted: showCompleted,
            #showInProgress: showInProgress,
            #selectedDateFilter: selectedDateFilter,
            #sortOption: sortOption,
          },
        ),
        returnValue: <_i6.CustomList>[],
      ) as List<_i6.CustomList>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
