// Mocks generated by Mockito 5.4.4 from annotations
// in prioris/test/application/services/data_migration_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prioris/domain/list/repositories/custom_list_repository.dart'
    as _i2;
import 'package:prioris/domain/models/core/entities/custom_list.dart' as _i4;
import 'package:prioris/domain/models/core/enums/list_enums.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CustomListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomListRepository extends _i1.Mock
    implements _i2.CustomListRepository {
  MockCustomListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<_i4.CustomList>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i3.Future<List<_i4.CustomList>>.value(<_i4.CustomList>[]),
      ) as _i3.Future<List<_i4.CustomList>>);

  @override
  _i3.Future<_i4.CustomList?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i3.Future<_i4.CustomList?>.value(),
      ) as _i3.Future<_i4.CustomList?>);

  @override
  _i3.Future<void> save(_i4.CustomList? entity) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [entity],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> update(_i4.CustomList? entity) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.CustomList>> getAllLists() => (super.noSuchMethod(
        Invocation.method(
          #getAllLists,
          [],
        ),
        returnValue: _i3.Future<List<_i4.CustomList>>.value(<_i4.CustomList>[]),
      ) as _i3.Future<List<_i4.CustomList>>);

  @override
  _i3.Future<_i4.CustomList?> getListById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getListById,
          [id],
        ),
        returnValue: _i3.Future<_i4.CustomList?>.value(),
      ) as _i3.Future<_i4.CustomList?>);

  @override
  _i3.Future<void> saveList(_i4.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #saveList,
          [list],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateList(_i4.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #updateList,
          [list],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteList(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.CustomList>> searchByName(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByName,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.CustomList>>.value(<_i4.CustomList>[]),
      ) as _i3.Future<List<_i4.CustomList>>);

  @override
  _i3.Future<List<_i4.CustomList>> searchByDescription(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByDescription,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.CustomList>>.value(<_i4.CustomList>[]),
      ) as _i3.Future<List<_i4.CustomList>>);

  @override
  _i3.Future<List<_i4.CustomList>> searchListsByName(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchListsByName,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.CustomList>>.value(<_i4.CustomList>[]),
      ) as _i3.Future<List<_i4.CustomList>>);

  @override
  _i3.Future<List<_i4.CustomList>> searchListsByDescription(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchListsByDescription,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.CustomList>>.value(<_i4.CustomList>[]),
      ) as _i3.Future<List<_i4.CustomList>>);

  @override
  _i3.Future<List<_i4.CustomList>> getByType(_i5.ListType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByType,
          [type],
        ),
        returnValue: _i3.Future<List<_i4.CustomList>>.value(<_i4.CustomList>[]),
      ) as _i3.Future<List<_i4.CustomList>>);

  @override
  _i3.Future<List<_i4.CustomList>> getListsByType(_i5.ListType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListsByType,
          [type],
        ),
        returnValue: _i3.Future<List<_i4.CustomList>>.value(<_i4.CustomList>[]),
      ) as _i3.Future<List<_i4.CustomList>>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllLists() => (super.noSuchMethod(
        Invocation.method(
          #clearAllLists,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
