// Mocks generated by Mockito 5.4.4 from annotations
// in prioris/test/application/services/lists_persistence_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prioris/data/repositories/custom_list_repository.dart' as _i2;
import 'package:prioris/data/repositories/list_item_repository.dart' as _i3;
import 'package:prioris/domain/models/core/entities/custom_list.dart' as _i7;
import 'package:prioris/domain/models/core/entities/list_item.dart' as _i4;
import 'package:prioris/domain/models/core/enums/list_enums.dart' as _i8;
import 'package:prioris/domain/services/persistence/adaptive_persistence_service.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCustomListRepository_0 extends _i1.SmartFake
    implements _i2.CustomListRepository {
  _FakeCustomListRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListItemRepository_1 extends _i1.SmartFake
    implements _i3.ListItemRepository {
  _FakeListItemRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListItem_2 extends _i1.SmartFake implements _i4.ListItem {
  _FakeListItem_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdaptivePersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdaptivePersistenceService extends _i1.Mock
    implements _i5.AdaptivePersistenceService {
  MockAdaptivePersistenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CustomListRepository get localRepository => (super.noSuchMethod(
        Invocation.getter(#localRepository),
        returnValue: _FakeCustomListRepository_0(
          this,
          Invocation.getter(#localRepository),
        ),
      ) as _i2.CustomListRepository);

  @override
  _i2.CustomListRepository get cloudRepository => (super.noSuchMethod(
        Invocation.getter(#cloudRepository),
        returnValue: _FakeCustomListRepository_0(
          this,
          Invocation.getter(#cloudRepository),
        ),
      ) as _i2.CustomListRepository);

  @override
  _i3.ListItemRepository get localItemRepository => (super.noSuchMethod(
        Invocation.getter(#localItemRepository),
        returnValue: _FakeListItemRepository_1(
          this,
          Invocation.getter(#localItemRepository),
        ),
      ) as _i3.ListItemRepository);

  @override
  _i3.ListItemRepository get cloudItemRepository => (super.noSuchMethod(
        Invocation.getter(#cloudItemRepository),
        returnValue: _FakeListItemRepository_1(
          this,
          Invocation.getter(#cloudItemRepository),
        ),
      ) as _i3.ListItemRepository);

  @override
  _i5.PersistenceMode get currentMode => (super.noSuchMethod(
        Invocation.getter(#currentMode),
        returnValue: _i5.PersistenceMode.localFirst,
      ) as _i5.PersistenceMode);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> initialize({bool? isAuthenticated}) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {#isAuthenticated: isAuthenticated},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateAuthenticationState(
          {required bool? isAuthenticated}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAuthenticationState,
          [],
          {#isAuthenticated: isAuthenticated},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.CustomList>> getAllLists() => (super.noSuchMethod(
        Invocation.method(
          #getAllLists,
          [],
        ),
        returnValue: _i6.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i6.Future<List<_i7.CustomList>>);

  @override
  _i6.Future<List<_i7.CustomList>> getLists() => (super.noSuchMethod(
        Invocation.method(
          #getLists,
          [],
        ),
        returnValue: _i6.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i6.Future<List<_i7.CustomList>>);

  @override
  _i6.Future<void> saveList(_i7.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #saveList,
          [list],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteList(String? listId) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [listId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i4.ListItem>> getItemsByListId(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByListId,
          [listId],
        ),
        returnValue: _i6.Future<List<_i4.ListItem>>.value(<_i4.ListItem>[]),
      ) as _i6.Future<List<_i4.ListItem>>);

  @override
  _i6.Future<List<_i4.ListItem>> getListItems(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListItems,
          [listId],
        ),
        returnValue: _i6.Future<List<_i4.ListItem>>.value(<_i4.ListItem>[]),
      ) as _i6.Future<List<_i4.ListItem>>);

  @override
  _i6.Future<void> saveItem(_i4.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #saveItem,
          [item],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateItem(_i4.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteItem(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [itemId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [CustomListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomListRepository extends _i1.Mock
    implements _i2.CustomListRepository {
  MockCustomListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<Map<String, dynamic>> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<_i7.CustomList>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i6.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i6.Future<List<_i7.CustomList>>);

  @override
  _i6.Future<_i7.CustomList?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i6.Future<_i7.CustomList?>.value(),
      ) as _i6.Future<_i7.CustomList?>);

  @override
  _i6.Future<void> save(_i7.CustomList? entity) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [entity],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> update(_i7.CustomList? entity) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [entity],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.CustomList>> getAllLists() => (super.noSuchMethod(
        Invocation.method(
          #getAllLists,
          [],
        ),
        returnValue: _i6.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i6.Future<List<_i7.CustomList>>);

  @override
  _i6.Future<_i7.CustomList?> getListById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getListById,
          [id],
        ),
        returnValue: _i6.Future<_i7.CustomList?>.value(),
      ) as _i6.Future<_i7.CustomList?>);

  @override
  _i6.Future<void> saveList(_i7.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #saveList,
          [list],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateList(_i7.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #updateList,
          [list],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteList(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.CustomList>> searchByName(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByName,
          [query],
        ),
        returnValue: _i6.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i6.Future<List<_i7.CustomList>>);

  @override
  _i6.Future<List<_i7.CustomList>> searchByDescription(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByDescription,
          [query],
        ),
        returnValue: _i6.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i6.Future<List<_i7.CustomList>>);

  @override
  _i6.Future<List<_i7.CustomList>> searchListsByName(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchListsByName,
          [query],
        ),
        returnValue: _i6.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i6.Future<List<_i7.CustomList>>);

  @override
  _i6.Future<List<_i7.CustomList>> searchListsByDescription(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchListsByDescription,
          [query],
        ),
        returnValue: _i6.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i6.Future<List<_i7.CustomList>>);

  @override
  _i6.Future<List<_i7.CustomList>> getByType(_i8.ListType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByType,
          [type],
        ),
        returnValue: _i6.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i6.Future<List<_i7.CustomList>>);

  @override
  _i6.Future<List<_i7.CustomList>> getListsByType(_i8.ListType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListsByType,
          [type],
        ),
        returnValue: _i6.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i6.Future<List<_i7.CustomList>>);

  @override
  _i6.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllLists() => (super.noSuchMethod(
        Invocation.method(
          #clearAllLists,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ListItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockListItemRepository extends _i1.Mock
    implements _i3.ListItemRepository {
  MockListItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i4.ListItem>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i6.Future<List<_i4.ListItem>>.value(<_i4.ListItem>[]),
      ) as _i6.Future<List<_i4.ListItem>>);

  @override
  _i6.Future<_i4.ListItem?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i6.Future<_i4.ListItem?>.value(),
      ) as _i6.Future<_i4.ListItem?>);

  @override
  _i6.Future<_i4.ListItem> add(_i4.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [item],
        ),
        returnValue: _i6.Future<_i4.ListItem>.value(_FakeListItem_2(
          this,
          Invocation.method(
            #add,
            [item],
          ),
        )),
      ) as _i6.Future<_i4.ListItem>);

  @override
  _i6.Future<_i4.ListItem> update(_i4.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [item],
        ),
        returnValue: _i6.Future<_i4.ListItem>.value(_FakeListItem_2(
          this,
          Invocation.method(
            #update,
            [item],
          ),
        )),
      ) as _i6.Future<_i4.ListItem>);

  @override
  _i6.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i4.ListItem>> getByListId(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByListId,
          [listId],
        ),
        returnValue: _i6.Future<List<_i4.ListItem>>.value(<_i4.ListItem>[]),
      ) as _i6.Future<List<_i4.ListItem>>);
}
