// Mocks generated by Mockito 5.4.4 from annotations
// in prioris/test/application/services/lists_transaction_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prioris/core/interfaces/lists_interfaces.dart' as _i2;
import 'package:prioris/domain/models/core/entities/custom_list.dart' as _i4;
import 'package:prioris/domain/models/core/entities/list_item.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IListsPersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIListsPersistenceService extends _i1.Mock
    implements _i2.IListsPersistenceService {
  MockIListsPersistenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CustomList>> getAllLists() => (super.noSuchMethod(
        Invocation.method(
          #getAllLists,
          [],
        ),
        returnValue: _i3.Future<List<_i4.CustomList>>.value(<_i4.CustomList>[]),
      ) as _i3.Future<List<_i4.CustomList>>);

  @override
  _i3.Future<_i4.CustomList?> getListById(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListById,
          [listId],
        ),
        returnValue: _i3.Future<_i4.CustomList?>.value(),
      ) as _i3.Future<_i4.CustomList?>);

  @override
  _i3.Future<void> saveList(_i4.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #saveList,
          [list],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteList(String? listId) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [listId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.ListItem>> getItemsByListId(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByListId,
          [listId],
        ),
        returnValue: _i3.Future<List<_i5.ListItem>>.value(<_i5.ListItem>[]),
      ) as _i3.Future<List<_i5.ListItem>>);

  @override
  _i3.Future<void> saveItem(_i5.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #saveItem,
          [item],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateItem(_i5.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteItem(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [itemId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> verifyPersistence(String? id) => (super.noSuchMethod(
        Invocation.method(
          #verifyPersistence,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> forceReload() => (super.noSuchMethod(
        Invocation.method(
          #forceReload,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
