// Mocks generated by Mockito 5.4.4 from annotations
// in prioris/test/integration/duel_list_item_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prioris/data/repositories/custom_list_repository.dart' as _i6;
import 'package:prioris/data/repositories/list_item_repository.dart' as _i9;
import 'package:prioris/data/repositories/task_repository.dart' as _i3;
import 'package:prioris/domain/models/core/entities/custom_list.dart' as _i7;
import 'package:prioris/domain/models/core/entities/list_item.dart' as _i2;
import 'package:prioris/domain/models/core/entities/task.dart' as _i5;
import 'package:prioris/domain/models/core/enums/list_enums.dart' as _i8;
import 'package:prioris/domain/services/core/lists_filter_service.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeListItem_0 extends _i1.SmartFake implements _i2.ListItem {
  _FakeListItem_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  @override
  _i4.Future<List<_i5.Task>> getAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
      ) as _i4.Future<List<_i5.Task>>);

  @override
  _i4.Future<void> saveTask(_i5.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #saveTask,
          [task],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTask(_i5.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [taskId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Task>> getActiveTasks() => (super.noSuchMethod(
        Invocation.method(
          #getActiveTasks,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
      ) as _i4.Future<List<_i5.Task>>);

  @override
  _i4.Future<List<_i5.Task>> getCompletedTasks() => (super.noSuchMethod(
        Invocation.method(
          #getCompletedTasks,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
      ) as _i4.Future<List<_i5.Task>>);

  @override
  _i4.Future<List<_i5.Task>> getTasksByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByCategory,
          [category],
        ),
        returnValue: _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
      ) as _i4.Future<List<_i5.Task>>);

  @override
  _i4.Future<void> clearAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #clearAllTasks,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateEloScores(
    _i5.Task? winner,
    _i5.Task? loser,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEloScores,
          [
            winner,
            loser,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Task>> getRandomTasksForDuel() => (super.noSuchMethod(
        Invocation.method(
          #getRandomTasksForDuel,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Task>>.value(<_i5.Task>[]),
      ) as _i4.Future<List<_i5.Task>>);
}

/// A class which mocks [CustomListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomListRepository extends _i1.Mock
    implements _i6.CustomListRepository {
  @override
  _i4.Future<Map<String, dynamic>> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i7.CustomList>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i4.Future<List<_i7.CustomList>>);

  @override
  _i4.Future<_i7.CustomList?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i4.Future<_i7.CustomList?>.value(),
        returnValueForMissingStub: _i4.Future<_i7.CustomList?>.value(),
      ) as _i4.Future<_i7.CustomList?>);

  @override
  _i4.Future<void> save(_i7.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [list],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> update(_i7.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [list],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.CustomList>> getAllLists() => (super.noSuchMethod(
        Invocation.method(
          #getAllLists,
          [],
        ),
        returnValue: _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i4.Future<List<_i7.CustomList>>);

  @override
  _i4.Future<_i7.CustomList?> getListById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getListById,
          [id],
        ),
        returnValue: _i4.Future<_i7.CustomList?>.value(),
        returnValueForMissingStub: _i4.Future<_i7.CustomList?>.value(),
      ) as _i4.Future<_i7.CustomList?>);

  @override
  _i4.Future<void> saveList(_i7.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #saveList,
          [list],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateList(_i7.CustomList? list) => (super.noSuchMethod(
        Invocation.method(
          #updateList,
          [list],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteList(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteList,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.CustomList>> searchByName(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByName,
          [query],
        ),
        returnValue: _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i4.Future<List<_i7.CustomList>>);

  @override
  _i4.Future<List<_i7.CustomList>> searchByDescription(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByDescription,
          [query],
        ),
        returnValue: _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i4.Future<List<_i7.CustomList>>);

  @override
  _i4.Future<List<_i7.CustomList>> searchListsByName(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchListsByName,
          [query],
        ),
        returnValue: _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i4.Future<List<_i7.CustomList>>);

  @override
  _i4.Future<List<_i7.CustomList>> searchListsByDescription(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchListsByDescription,
          [query],
        ),
        returnValue: _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i4.Future<List<_i7.CustomList>>);

  @override
  _i4.Future<List<_i7.CustomList>> getByType(_i8.ListType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByType,
          [type],
        ),
        returnValue: _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i4.Future<List<_i7.CustomList>>);

  @override
  _i4.Future<List<_i7.CustomList>> getListsByType(_i8.ListType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListsByType,
          [type],
        ),
        returnValue: _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.CustomList>>.value(<_i7.CustomList>[]),
      ) as _i4.Future<List<_i7.CustomList>>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllLists() => (super.noSuchMethod(
        Invocation.method(
          #clearAllLists,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ListItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockListItemRepository extends _i1.Mock
    implements _i9.ListItemRepository {
  @override
  _i4.Future<List<_i2.ListItem>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<List<_i2.ListItem>>.value(<_i2.ListItem>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.ListItem>>.value(<_i2.ListItem>[]),
      ) as _i4.Future<List<_i2.ListItem>>);

  @override
  _i4.Future<_i2.ListItem?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i4.Future<_i2.ListItem?>.value(),
        returnValueForMissingStub: _i4.Future<_i2.ListItem?>.value(),
      ) as _i4.Future<_i2.ListItem?>);

  @override
  _i4.Future<_i2.ListItem> add(_i2.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [item],
        ),
        returnValue: _i4.Future<_i2.ListItem>.value(_FakeListItem_0(
          this,
          Invocation.method(
            #add,
            [item],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ListItem>.value(_FakeListItem_0(
          this,
          Invocation.method(
            #add,
            [item],
          ),
        )),
      ) as _i4.Future<_i2.ListItem>);

  @override
  _i4.Future<_i2.ListItem> update(_i2.ListItem? item) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [item],
        ),
        returnValue: _i4.Future<_i2.ListItem>.value(_FakeListItem_0(
          this,
          Invocation.method(
            #update,
            [item],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ListItem>.value(_FakeListItem_0(
          this,
          Invocation.method(
            #update,
            [item],
          ),
        )),
      ) as _i4.Future<_i2.ListItem>);

  @override
  _i4.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.ListItem>> getByListId(String? listId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByListId,
          [listId],
        ),
        returnValue: _i4.Future<List<_i2.ListItem>>.value(<_i2.ListItem>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.ListItem>>.value(<_i2.ListItem>[]),
      ) as _i4.Future<List<_i2.ListItem>>);
}

/// A class which mocks [ListsFilterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockListsFilterService extends _i1.Mock
    implements _i10.ListsFilterService {
  @override
  List<_i7.CustomList> applyFilters(
    List<_i7.CustomList>? lists, {
    String? searchQuery = r'',
    _i8.ListType? selectedType,
    bool? showCompleted = true,
    bool? showInProgress = true,
    String? selectedDateFilter,
    _i10.SortOption? sortOption = _i10.SortOption.NAME_ASC,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyFilters,
          [lists],
          {
            #searchQuery: searchQuery,
            #selectedType: selectedType,
            #showCompleted: showCompleted,
            #showInProgress: showInProgress,
            #selectedDateFilter: selectedDateFilter,
            #sortOption: sortOption,
          },
        ),
        returnValue: <_i7.CustomList>[],
        returnValueForMissingStub: <_i7.CustomList>[],
      ) as List<_i7.CustomList>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
